// Generated by scripts/generate-database-types.mjs from the canonical migration replay.
// Do not edit by hand.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      "accounting_journal_entries": {
        Row: {
          "id": string
          "center_id": string
          "entry_date": string
          "entry_type": string
          "reference_type": string | null
          "reference_id": string | null
          "description": string
          "debit_account": string
          "credit_account": string
          "amount": number
          "currency": string
          "created_by": string | null
          "created_at": string
          "updated_at": string
        }
        Insert: {
          "id"?: string
          "center_id": string
          "entry_date"?: string
          "entry_type": string
          "reference_type"?: string | null
          "reference_id"?: string | null
          "description": string
          "debit_account": string
          "credit_account": string
          "amount": number
          "currency"?: string
          "created_by"?: string | null
          "created_at"?: string
          "updated_at"?: string
        }
        Update: {
          "id"?: string
          "center_id"?: string
          "entry_date"?: string
          "entry_type"?: string
          "reference_type"?: string | null
          "reference_id"?: string | null
          "description"?: string
          "debit_account"?: string
          "credit_account"?: string
          "amount"?: number
          "currency"?: string
          "created_by"?: string | null
          "created_at"?: string
          "updated_at"?: string
        }
        Relationships: [
          {
            foreignKeyName: "accounting_journal_entries_center_id_fkey"
            columns: ["center_id"]
            isOneToOne: false
            referencedRelation: "centers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "accounting_journal_entries_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
      "admin_audit_events": {
        Row: {
          "id": string
          "center_id": string
          "actor_id": string
          "actor_name": string
          "action": string
          "target_type": string
          "target_id": string | null
          "target_summary": string | null
          "reason": string | null
          "details": Json | null
          "created_at": string
        }
        Insert: {
          "id"?: string
          "center_id": string
          "actor_id": string
          "actor_name"?: string
          "action": string
          "target_type": string
          "target_id"?: string | null
          "target_summary"?: string | null
          "reason"?: string | null
          "details"?: Json | null
          "created_at"?: string
        }
        Update: {
          "id"?: string
          "center_id"?: string
          "actor_id"?: string
          "actor_name"?: string
          "action"?: string
          "target_type"?: string
          "target_id"?: string | null
          "target_summary"?: string | null
          "reason"?: string | null
          "details"?: Json | null
          "created_at"?: string
        }
        Relationships: [
          {
            foreignKeyName: "admin_audit_events_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "admin_audit_events_center_id_fkey"
            columns: ["center_id"]
            isOneToOne: false
            referencedRelation: "centers"
            referencedColumns: ["id"]
          }
        ]
      }
      "ai_booking_leads": {
        Row: {
          "id": string
          "center_id": string
          "customer_name": string
          "customer_phone": string | null
          "preferred_service_id": string | null
          "preferred_date": string | null
          "source_channel": string
          "status": string
          "summary": string | null
          "created_at": string
          "updated_at": string
        }
        Insert: {
          "id"?: string
          "center_id": string
          "customer_name": string
          "customer_phone"?: string | null
          "preferred_service_id"?: string | null
          "preferred_date"?: string | null
          "source_channel"?: string
          "status"?: string
          "summary"?: string | null
          "created_at"?: string
          "updated_at"?: string
        }
        Update: {
          "id"?: string
          "center_id"?: string
          "customer_name"?: string
          "customer_phone"?: string | null
          "preferred_service_id"?: string | null
          "preferred_date"?: string | null
          "source_channel"?: string
          "status"?: string
          "summary"?: string | null
          "created_at"?: string
          "updated_at"?: string
        }
        Relationships: [
          {
            foreignKeyName: "ai_booking_leads_center_id_fkey"
            columns: ["center_id"]
            isOneToOne: false
            referencedRelation: "centers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ai_booking_leads_preferred_service_id_fkey"
            columns: ["preferred_service_id"]
            isOneToOne: false
            referencedRelation: "services"
            referencedColumns: ["id"]
          }
        ]
      }
      "appointments": {
        Row: {
          "id": string
          "center_id": string
          "customer_id": string
          "employee_id": string | null
          "service_id": string | null
          "date_time": string
          "status": Database["public"]["Enums"]["appointment_status"]
          "notes": string | null
          "created_at": string
          "updated_at": string
          "deposit_amount": number
          "no_show_fee_amount": number
          "no_show_fee_charged": number
          "no_show_marked_at": string | null
          "no_show_note": string | null
          "cancellation_reason": string | null
          "cancelled_at": string | null
          "rescheduled_from_appointment_id": string | null
          "rescheduled_at": string | null
          "booking_source": string
          "duration_minutes_snapshot": number | null
        }
        Insert: {
          "id"?: string
          "center_id": string
          "customer_id": string
          "employee_id"?: string | null
          "service_id"?: string | null
          "date_time": string
          "status"?: Database["public"]["Enums"]["appointment_status"]
          "notes"?: string | null
          "created_at"?: string
          "updated_at"?: string
          "deposit_amount"?: number
          "no_show_fee_amount"?: number
          "no_show_fee_charged"?: number
          "no_show_marked_at"?: string | null
          "no_show_note"?: string | null
          "cancellation_reason"?: string | null
          "cancelled_at"?: string | null
          "rescheduled_from_appointment_id"?: string | null
          "rescheduled_at"?: string | null
          "booking_source"?: string
          "duration_minutes_snapshot"?: number | null
        }
        Update: {
          "id"?: string
          "center_id"?: string
          "customer_id"?: string
          "employee_id"?: string | null
          "service_id"?: string | null
          "date_time"?: string
          "status"?: Database["public"]["Enums"]["appointment_status"]
          "notes"?: string | null
          "created_at"?: string
          "updated_at"?: string
          "deposit_amount"?: number
          "no_show_fee_amount"?: number
          "no_show_fee_charged"?: number
          "no_show_marked_at"?: string | null
          "no_show_note"?: string | null
          "cancellation_reason"?: string | null
          "cancelled_at"?: string | null
          "rescheduled_from_appointment_id"?: string | null
          "rescheduled_at"?: string | null
          "booking_source"?: string
          "duration_minutes_snapshot"?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "appointments_center_id_fkey"
            columns: ["center_id"]
            isOneToOne: false
            referencedRelation: "centers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "appointments_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "appointments_employee_id_fkey"
            columns: ["employee_id"]
            isOneToOne: false
            referencedRelation: "employees"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "appointments_rescheduled_from_appointment_id_fkey"
            columns: ["rescheduled_from_appointment_id"]
            isOneToOne: false
            referencedRelation: "appointments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "appointments_service_id_fkey"
            columns: ["service_id"]
            isOneToOne: false
            referencedRelation: "services"
            referencedColumns: ["id"]
          }
        ]
      }
      "attendance_records": {
        Row: {
          "id": string
          "center_id": string
          "employee_id": string
          "date": string
          "check_in_time": string | null
          "check_out_time": string | null
          "method": string
          "work_hours": number
          "status": string
          "notes": string | null
          "created_at": string
          "updated_at": string
        }
        Insert: {
          "id"?: string
          "center_id": string
          "employee_id": string
          "date": string
          "check_in_time"?: string | null
          "check_out_time"?: string | null
          "method"?: string
          "work_hours"?: number
          "status"?: string
          "notes"?: string | null
          "created_at"?: string
          "updated_at"?: string
        }
        Update: {
          "id"?: string
          "center_id"?: string
          "employee_id"?: string
          "date"?: string
          "check_in_time"?: string | null
          "check_out_time"?: string | null
          "method"?: string
          "work_hours"?: number
          "status"?: string
          "notes"?: string | null
          "created_at"?: string
          "updated_at"?: string
        }
        Relationships: [
          {
            foreignKeyName: "attendance_employee_center_fk"
            columns: ["employee_id", "center_id"]
            isOneToOne: false
            referencedRelation: "employees"
            referencedColumns: ["id", "center_id"]
          },
          {
            foreignKeyName: "attendance_records_center_id_fkey"
            columns: ["center_id"]
            isOneToOne: false
            referencedRelation: "centers"
            referencedColumns: ["id"]
          }
        ]
      }
      "center_memberships": {
        Row: {
          "id": string
          "profile_id": string
          "center_id": string
          "role": string
          "created_at": string
        }
        Insert: {
          "id"?: string
          "profile_id": string
          "center_id": string
          "role"?: string
          "created_at"?: string
        }
        Update: {
          "id"?: string
          "profile_id"?: string
          "center_id"?: string
          "role"?: string
          "created_at"?: string
        }
        Relationships: [
          {
            foreignKeyName: "center_memberships_center_id_fkey"
            columns: ["center_id"]
            isOneToOne: false
            referencedRelation: "centers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "center_memberships_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          }
        ]
      }
      "center_settings": {
        Row: {
          "id": string
          "center_id": string
          "name": string
          "currency": string
          "tax_rate": number
          "logo_path": string | null
          "address": string | null
          "phone": string | null
          "cr": string | null
          "postal_code": string | null
          "created_at": string
          "updated_at": string
          "display_name": string | null
          "display_name_ar": string | null
          "brand_email": string | null
          "brand_tax_number": string | null
          "brand_registration_number": string | null
          "brand_primary_color": string | null
          "brand_secondary_color": string | null
          "brand_accent_color": string | null
          "brand_footer_text": string | null
          "brand_footer_text_ar": string | null
          "brand_logo_base64": string | null
        }
        Insert: {
          "id"?: string
          "center_id": string
          "name"?: string
          "currency"?: string
          "tax_rate"?: number
          "logo_path"?: string | null
          "address"?: string | null
          "phone"?: string | null
          "cr"?: string | null
          "postal_code"?: string | null
          "created_at"?: string
          "updated_at"?: string
          "display_name"?: string | null
          "display_name_ar"?: string | null
          "brand_email"?: string | null
          "brand_tax_number"?: string | null
          "brand_registration_number"?: string | null
          "brand_primary_color"?: string | null
          "brand_secondary_color"?: string | null
          "brand_accent_color"?: string | null
          "brand_footer_text"?: string | null
          "brand_footer_text_ar"?: string | null
          "brand_logo_base64"?: string | null
        }
        Update: {
          "id"?: string
          "center_id"?: string
          "name"?: string
          "currency"?: string
          "tax_rate"?: number
          "logo_path"?: string | null
          "address"?: string | null
          "phone"?: string | null
          "cr"?: string | null
          "postal_code"?: string | null
          "created_at"?: string
          "updated_at"?: string
          "display_name"?: string | null
          "display_name_ar"?: string | null
          "brand_email"?: string | null
          "brand_tax_number"?: string | null
          "brand_registration_number"?: string | null
          "brand_primary_color"?: string | null
          "brand_secondary_color"?: string | null
          "brand_accent_color"?: string | null
          "brand_footer_text"?: string | null
          "brand_footer_text_ar"?: string | null
          "brand_logo_base64"?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "center_settings_center_id_fkey"
            columns: ["center_id"]
            isOneToOne: false
            referencedRelation: "centers"
            referencedColumns: ["id"]
          }
        ]
      }
      "centers": {
        Row: {
          "id": string
          "name": string
          "created_at": string
          "updated_at": string
        }
        Insert: {
          "id"?: string
          "name": string
          "created_at"?: string
          "updated_at"?: string
        }
        Update: {
          "id"?: string
          "name"?: string
          "created_at"?: string
          "updated_at"?: string
        }
        Relationships: [
          
        ]
      }
      "checkout_idempotency": {
        Row: {
          "center_id": string
          "request_id": string
          "invoice_id": string | null
          "result": Json | null
          "created_at": string
          "completed_at": string | null
        }
        Insert: {
          "center_id": string
          "request_id": string
          "invoice_id"?: string | null
          "result"?: Json | null
          "created_at"?: string
          "completed_at"?: string | null
        }
        Update: {
          "center_id"?: string
          "request_id"?: string
          "invoice_id"?: string | null
          "result"?: Json | null
          "created_at"?: string
          "completed_at"?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "checkout_idempotency_center_id_fkey"
            columns: ["center_id"]
            isOneToOne: false
            referencedRelation: "centers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "checkout_idempotency_invoice_id_fkey"
            columns: ["invoice_id"]
            isOneToOne: false
            referencedRelation: "invoices"
            referencedColumns: ["id"]
          }
        ]
      }
      "customer_entitlements": {
        Row: {
          "id": string
          "center_id": string
          "customer_id": string | null
          "kind": string
          "gift_card_id": string | null
          "package_id": string | null
          "source_invoice_id": string | null
          "original_value": number
          "remaining_value": number
          "status": string
          "expires_at": string | null
          "legacy_flag": boolean
          "created_at": string
          "updated_at": string
        }
        Insert: {
          "id"?: string
          "center_id": string
          "customer_id"?: string | null
          "kind": string
          "gift_card_id"?: string | null
          "package_id"?: string | null
          "source_invoice_id"?: string | null
          "original_value": number
          "remaining_value": number
          "status"?: string
          "expires_at"?: string | null
          "legacy_flag"?: boolean
          "created_at"?: string
          "updated_at"?: string
        }
        Update: {
          "id"?: string
          "center_id"?: string
          "customer_id"?: string | null
          "kind"?: string
          "gift_card_id"?: string | null
          "package_id"?: string | null
          "source_invoice_id"?: string | null
          "original_value"?: number
          "remaining_value"?: number
          "status"?: string
          "expires_at"?: string | null
          "legacy_flag"?: boolean
          "created_at"?: string
          "updated_at"?: string
        }
        Relationships: [
          {
            foreignKeyName: "customer_entitlements_center_id_fkey"
            columns: ["center_id"]
            isOneToOne: false
            referencedRelation: "centers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "customer_entitlements_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "customer_entitlements_gift_card_id_fkey"
            columns: ["gift_card_id"]
            isOneToOne: false
            referencedRelation: "gift_cards"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "customer_entitlements_package_id_fkey"
            columns: ["package_id"]
            isOneToOne: false
            referencedRelation: "service_packages"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "customer_entitlements_source_invoice_id_fkey"
            columns: ["source_invoice_id"]
            isOneToOne: false
            referencedRelation: "invoices"
            referencedColumns: ["id"]
          }
        ]
      }
      "customer_notification_preferences": {
        Row: {
          "id": string
          "center_id": string
          "customer_id": string
          "channel": string
          "opt_in": boolean
          "opt_in_token": string | null
          "quiet_hour_start": string | null
          "quiet_hour_end": string | null
          "updated_at": string
        }
        Insert: {
          "id"?: string
          "center_id": string
          "customer_id": string
          "channel": string
          "opt_in"?: boolean
          "opt_in_token"?: string | null
          "quiet_hour_start"?: string | null
          "quiet_hour_end"?: string | null
          "updated_at"?: string
        }
        Update: {
          "id"?: string
          "center_id"?: string
          "customer_id"?: string
          "channel"?: string
          "opt_in"?: boolean
          "opt_in_token"?: string | null
          "quiet_hour_start"?: string | null
          "quiet_hour_end"?: string | null
          "updated_at"?: string
        }
        Relationships: [
          {
            foreignKeyName: "customer_notification_preferences_center_id_fkey"
            columns: ["center_id"]
            isOneToOne: false
            referencedRelation: "centers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "customer_notification_preferences_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          }
        ]
      }
      "customer_notification_timeline": {
        Row: {
          "id": string
          "center_id": string
          "customer_id": string
          "appointment_id": string | null
          "channel": string
          "direction": string
          "template_key": string | null
          "message_preview": string
          "delivery_status": string
          "sent_at": string | null
          "created_at": string
          "dedup_key": string | null
        }
        Insert: {
          "id"?: string
          "center_id": string
          "customer_id": string
          "appointment_id"?: string | null
          "channel": string
          "direction"?: string
          "template_key"?: string | null
          "message_preview": string
          "delivery_status"?: string
          "sent_at"?: string | null
          "created_at"?: string
          "dedup_key"?: string | null
        }
        Update: {
          "id"?: string
          "center_id"?: string
          "customer_id"?: string
          "appointment_id"?: string | null
          "channel"?: string
          "direction"?: string
          "template_key"?: string | null
          "message_preview"?: string
          "delivery_status"?: string
          "sent_at"?: string | null
          "created_at"?: string
          "dedup_key"?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "customer_notification_timeline_appointment_id_fkey"
            columns: ["appointment_id"]
            isOneToOne: false
            referencedRelation: "appointments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "customer_notification_timeline_center_id_fkey"
            columns: ["center_id"]
            isOneToOne: false
            referencedRelation: "centers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "customer_notification_timeline_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          }
        ]
      }
      "customer_reviews": {
        Row: {
          "id": string
          "center_id": string
          "customer_id": string
          "appointment_id": string | null
          "rating": number
          "comment": string | null
          "is_published": boolean
          "created_at": string
          "updated_at": string
        }
        Insert: {
          "id"?: string
          "center_id": string
          "customer_id": string
          "appointment_id"?: string | null
          "rating": number
          "comment"?: string | null
          "is_published"?: boolean
          "created_at"?: string
          "updated_at"?: string
        }
        Update: {
          "id"?: string
          "center_id"?: string
          "customer_id"?: string
          "appointment_id"?: string | null
          "rating"?: number
          "comment"?: string | null
          "is_published"?: boolean
          "created_at"?: string
          "updated_at"?: string
        }
        Relationships: [
          {
            foreignKeyName: "customer_reviews_appointment_id_fkey"
            columns: ["appointment_id"]
            isOneToOne: false
            referencedRelation: "appointments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "customer_reviews_center_id_fkey"
            columns: ["center_id"]
            isOneToOne: false
            referencedRelation: "centers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "customer_reviews_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          }
        ]
      }
      "customer_support_notes": {
        Row: {
          "id": string
          "center_id": string
          "customer_id": string
          "actor_id": string
          "note": string
          "created_at": string
        }
        Insert: {
          "id"?: string
          "center_id": string
          "customer_id": string
          "actor_id": string
          "note": string
          "created_at"?: string
        }
        Update: {
          "id"?: string
          "center_id"?: string
          "customer_id"?: string
          "actor_id"?: string
          "note"?: string
          "created_at"?: string
        }
        Relationships: [
          {
            foreignKeyName: "customer_support_notes_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "customer_support_notes_center_id_fkey"
            columns: ["center_id"]
            isOneToOne: false
            referencedRelation: "centers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "customer_support_notes_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          }
        ]
      }
      "customers": {
        Row: {
          "id": string
          "center_id": string
          "name": string
          "category": string | null
          "phone": string | null
          "email": string | null
          "notes": string | null
          "total_spent": number
          "loyalty_points": number
          "last_visit": string | null
          "created_at": string
          "updated_at": string
          "portal_access_token": string | null
          "portal_access_enabled": boolean
          "portal_last_login_at": string | null
          "referral_code": string
          "referred_by_customer_id": string | null
          "referral_points_earned": number
          "portal_failed_login_attempts": number
          "portal_locked_until": string | null
        }
        Insert: {
          "id"?: string
          "center_id": string
          "name": string
          "category"?: string | null
          "phone"?: string | null
          "email"?: string | null
          "notes"?: string | null
          "total_spent"?: number
          "loyalty_points"?: number
          "last_visit"?: string | null
          "created_at"?: string
          "updated_at"?: string
          "portal_access_token"?: string | null
          "portal_access_enabled"?: boolean
          "portal_last_login_at"?: string | null
          "referral_code"?: string
          "referred_by_customer_id"?: string | null
          "referral_points_earned"?: number
          "portal_failed_login_attempts"?: number
          "portal_locked_until"?: string | null
        }
        Update: {
          "id"?: string
          "center_id"?: string
          "name"?: string
          "category"?: string | null
          "phone"?: string | null
          "email"?: string | null
          "notes"?: string | null
          "total_spent"?: number
          "loyalty_points"?: number
          "last_visit"?: string | null
          "created_at"?: string
          "updated_at"?: string
          "portal_access_token"?: string | null
          "portal_access_enabled"?: boolean
          "portal_last_login_at"?: string | null
          "referral_code"?: string
          "referred_by_customer_id"?: string | null
          "referral_points_earned"?: number
          "portal_failed_login_attempts"?: number
          "portal_locked_until"?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "customers_center_id_fkey"
            columns: ["center_id"]
            isOneToOne: false
            referencedRelation: "centers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "customers_referred_by_customer_id_fkey"
            columns: ["referred_by_customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          }
        ]
      }
      "employee_advances": {
        Row: {
          "id": string
          "center_id": string
          "employee_id": string
          "amount": number
          "reason": string | null
          "advance_date": string
          "status": string
          "deducted_in_run_id": string | null
          "notes": string | null
          "created_at": string
          "updated_at": string
        }
        Insert: {
          "id"?: string
          "center_id": string
          "employee_id": string
          "amount"?: number
          "reason"?: string | null
          "advance_date"?: string
          "status"?: string
          "deducted_in_run_id"?: string | null
          "notes"?: string | null
          "created_at"?: string
          "updated_at"?: string
        }
        Update: {
          "id"?: string
          "center_id"?: string
          "employee_id"?: string
          "amount"?: number
          "reason"?: string | null
          "advance_date"?: string
          "status"?: string
          "deducted_in_run_id"?: string | null
          "notes"?: string | null
          "created_at"?: string
          "updated_at"?: string
        }
        Relationships: [
          {
            foreignKeyName: "advances_employee_center_fk"
            columns: ["employee_id", "center_id"]
            isOneToOne: false
            referencedRelation: "employees"
            referencedColumns: ["id", "center_id"]
          },
          {
            foreignKeyName: "employee_advances_center_id_fkey"
            columns: ["center_id"]
            isOneToOne: false
            referencedRelation: "centers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "employee_advances_deducted_in_run_id_fkey"
            columns: ["deducted_in_run_id"]
            isOneToOne: false
            referencedRelation: "payroll_runs"
            referencedColumns: ["id"]
          }
        ]
      }
      "employees": {
        Row: {
          "id": string
          "center_id": string
          "name": string
          "phone": string | null
          "role": string
          "salary": number
          "base_salary": number
          "commission_percentage": number
          "month_commission_total": number
          "is_active": boolean
          "created_at": string
          "updated_at": string
        }
        Insert: {
          "id"?: string
          "center_id": string
          "name": string
          "phone"?: string | null
          "role"?: string
          "salary"?: number
          "base_salary"?: number
          "commission_percentage"?: number
          "month_commission_total"?: number
          "is_active"?: boolean
          "created_at"?: string
          "updated_at"?: string
        }
        Update: {
          "id"?: string
          "center_id"?: string
          "name"?: string
          "phone"?: string | null
          "role"?: string
          "salary"?: number
          "base_salary"?: number
          "commission_percentage"?: number
          "month_commission_total"?: number
          "is_active"?: boolean
          "created_at"?: string
          "updated_at"?: string
        }
        Relationships: [
          {
            foreignKeyName: "employees_center_id_fkey"
            columns: ["center_id"]
            isOneToOne: false
            referencedRelation: "centers"
            referencedColumns: ["id"]
          }
        ]
      }
      "entitlement_ledger": {
        Row: {
          "id": string
          "center_id": string
          "entitlement_id": string
          "entry_type": string
          "amount": number
          "units": number | null
          "service_id": string | null
          "invoice_id": string | null
          "actor_id": string | null
          "reason": string | null
          "legacy_flag": boolean
          "created_at": string
        }
        Insert: {
          "id"?: string
          "center_id": string
          "entitlement_id": string
          "entry_type": string
          "amount": number
          "units"?: number | null
          "service_id"?: string | null
          "invoice_id"?: string | null
          "actor_id"?: string | null
          "reason"?: string | null
          "legacy_flag"?: boolean
          "created_at"?: string
        }
        Update: {
          "id"?: string
          "center_id"?: string
          "entitlement_id"?: string
          "entry_type"?: string
          "amount"?: number
          "units"?: number | null
          "service_id"?: string | null
          "invoice_id"?: string | null
          "actor_id"?: string | null
          "reason"?: string | null
          "legacy_flag"?: boolean
          "created_at"?: string
        }
        Relationships: [
          {
            foreignKeyName: "entitlement_ledger_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "employees"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "entitlement_ledger_center_id_fkey"
            columns: ["center_id"]
            isOneToOne: false
            referencedRelation: "centers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "entitlement_ledger_entitlement_id_fkey"
            columns: ["entitlement_id"]
            isOneToOne: false
            referencedRelation: "customer_entitlements"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "entitlement_ledger_invoice_id_fkey"
            columns: ["invoice_id"]
            isOneToOne: false
            referencedRelation: "invoices"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "entitlement_ledger_service_id_fkey"
            columns: ["service_id"]
            isOneToOne: false
            referencedRelation: "services"
            referencedColumns: ["id"]
          }
        ]
      }
      "expenses": {
        Row: {
          "id": string
          "center_id": string
          "amount": number
          "category": string
          "description": string | null
          "date": string
          "created_at": string
        }
        Insert: {
          "id"?: string
          "center_id": string
          "amount"?: number
          "category": string
          "description"?: string | null
          "date"?: string
          "created_at"?: string
        }
        Update: {
          "id"?: string
          "center_id"?: string
          "amount"?: number
          "category"?: string
          "description"?: string | null
          "date"?: string
          "created_at"?: string
        }
        Relationships: [
          {
            foreignKeyName: "expenses_center_id_fkey"
            columns: ["center_id"]
            isOneToOne: false
            referencedRelation: "centers"
            referencedColumns: ["id"]
          }
        ]
      }
      "gift_card_transactions": {
        Row: {
          "id": string
          "gift_card_id": string
          "center_id": string
          "kind": string
          "amount": number
          "invoice_id": string | null
          "note": string | null
          "created_at": string
        }
        Insert: {
          "id"?: string
          "gift_card_id": string
          "center_id": string
          "kind": string
          "amount": number
          "invoice_id"?: string | null
          "note"?: string | null
          "created_at"?: string
        }
        Update: {
          "id"?: string
          "gift_card_id"?: string
          "center_id"?: string
          "kind"?: string
          "amount"?: number
          "invoice_id"?: string | null
          "note"?: string | null
          "created_at"?: string
        }
        Relationships: [
          {
            foreignKeyName: "gift_card_transactions_center_id_fkey"
            columns: ["center_id"]
            isOneToOne: false
            referencedRelation: "centers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "gift_card_transactions_gift_card_id_fkey"
            columns: ["gift_card_id"]
            isOneToOne: false
            referencedRelation: "gift_cards"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "gift_card_transactions_invoice_id_fkey"
            columns: ["invoice_id"]
            isOneToOne: false
            referencedRelation: "invoices"
            referencedColumns: ["id"]
          }
        ]
      }
      "gift_cards": {
        Row: {
          "id": string
          "center_id": string
          "code": string
          "initial_balance": number
          "current_balance": number
          "customer_id": string | null
          "note": string | null
          "expires_at": string | null
          "is_active": boolean
          "created_at": string
          "updated_at": string
        }
        Insert: {
          "id"?: string
          "center_id": string
          "code": string
          "initial_balance": number
          "current_balance": number
          "customer_id"?: string | null
          "note"?: string | null
          "expires_at"?: string | null
          "is_active"?: boolean
          "created_at"?: string
          "updated_at"?: string
        }
        Update: {
          "id"?: string
          "center_id"?: string
          "code"?: string
          "initial_balance"?: number
          "current_balance"?: number
          "customer_id"?: string | null
          "note"?: string | null
          "expires_at"?: string | null
          "is_active"?: boolean
          "created_at"?: string
          "updated_at"?: string
        }
        Relationships: [
          {
            foreignKeyName: "gift_cards_center_id_fkey"
            columns: ["center_id"]
            isOneToOne: false
            referencedRelation: "centers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "gift_cards_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          }
        ]
      }
      "invoice_items": {
        Row: {
          "id": string
          "invoice_id": string
          "service_id": string | null
          "product_id": string | null
          "price": number
          "quantity": number
          "created_at": string
          "package_id": string | null
          "item_type": string | null
          "item_name": string | null
          "gift_card_id": string | null
        }
        Insert: {
          "id"?: string
          "invoice_id": string
          "service_id"?: string | null
          "product_id"?: string | null
          "price"?: number
          "quantity"?: number
          "created_at"?: string
          "package_id"?: string | null
          "item_type"?: string | null
          "item_name"?: string | null
          "gift_card_id"?: string | null
        }
        Update: {
          "id"?: string
          "invoice_id"?: string
          "service_id"?: string | null
          "product_id"?: string | null
          "price"?: number
          "quantity"?: number
          "created_at"?: string
          "package_id"?: string | null
          "item_type"?: string | null
          "item_name"?: string | null
          "gift_card_id"?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "invoice_items_gift_card_id_fkey"
            columns: ["gift_card_id"]
            isOneToOne: false
            referencedRelation: "gift_cards"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "invoice_items_invoice_id_fkey"
            columns: ["invoice_id"]
            isOneToOne: false
            referencedRelation: "invoices"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "invoice_items_package_id_fkey"
            columns: ["package_id"]
            isOneToOne: false
            referencedRelation: "service_packages"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "invoice_items_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "invoice_items_service_id_fkey"
            columns: ["service_id"]
            isOneToOne: false
            referencedRelation: "services"
            referencedColumns: ["id"]
          }
        ]
      }
      "invoices": {
        Row: {
          "id": string
          "center_id": string
          "customer_id": string
          "serial_number": string | null
          "date": string
          "total_amount": number
          "discount": number
          "loyalty_points_used": number
          "payment_method": string
          "created_at": string
          "updated_at": string
          "employee_id": string | null
          "tax": number
          "subtotal_amount": number
          "manual_discount": number
          "tier_discount": number
          "loyalty_discount": number
          "gift_card_discount": number
          "tax_rate": number
          "amount_paid": number
          "status": string
          "entitlement_redemption": number
        }
        Insert: {
          "id"?: string
          "center_id": string
          "customer_id": string
          "serial_number"?: string | null
          "date"?: string
          "total_amount"?: number
          "discount"?: number
          "loyalty_points_used"?: number
          "payment_method"?: string
          "created_at"?: string
          "updated_at"?: string
          "employee_id"?: string | null
          "tax"?: number
          "subtotal_amount"?: number
          "manual_discount"?: number
          "tier_discount"?: number
          "loyalty_discount"?: number
          "gift_card_discount"?: number
          "tax_rate"?: number
          "amount_paid"?: number
          "status"?: string
          "entitlement_redemption"?: number
        }
        Update: {
          "id"?: string
          "center_id"?: string
          "customer_id"?: string
          "serial_number"?: string | null
          "date"?: string
          "total_amount"?: number
          "discount"?: number
          "loyalty_points_used"?: number
          "payment_method"?: string
          "created_at"?: string
          "updated_at"?: string
          "employee_id"?: string | null
          "tax"?: number
          "subtotal_amount"?: number
          "manual_discount"?: number
          "tier_discount"?: number
          "loyalty_discount"?: number
          "gift_card_discount"?: number
          "tax_rate"?: number
          "amount_paid"?: number
          "status"?: string
          "entitlement_redemption"?: number
        }
        Relationships: [
          {
            foreignKeyName: "invoices_center_id_fkey"
            columns: ["center_id"]
            isOneToOne: false
            referencedRelation: "centers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "invoices_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "invoices_employee_id_fkey"
            columns: ["employee_id"]
            isOneToOne: false
            referencedRelation: "employees"
            referencedColumns: ["id"]
          }
        ]
      }
      "notification_dedup_claims": {
        Row: {
          "center_id": string
          "dedup_key": string
          "claimed_at": string
        }
        Insert: {
          "center_id": string
          "dedup_key": string
          "claimed_at"?: string
        }
        Update: {
          "center_id"?: string
          "dedup_key"?: string
          "claimed_at"?: string
        }
        Relationships: [
          {
            foreignKeyName: "notification_dedup_claims_center_id_fkey"
            columns: ["center_id"]
            isOneToOne: false
            referencedRelation: "centers"
            referencedColumns: ["id"]
          }
        ]
      }
      "notification_settings": {
        Row: {
          "id": string
          "center_id": string
          "whatsapp_enabled": boolean
          "sms_enabled": boolean
          "reminder_enabled": boolean
          "reminder_hours_before": number
          "whatsapp_sender_name": string | null
          "sms_sender_name": string | null
          "whatsapp_template_booking": string | null
          "whatsapp_template_reminder": string | null
          "sms_template_reminder": string | null
          "created_at": string
          "updated_at": string
        }
        Insert: {
          "id"?: string
          "center_id": string
          "whatsapp_enabled"?: boolean
          "sms_enabled"?: boolean
          "reminder_enabled"?: boolean
          "reminder_hours_before"?: number
          "whatsapp_sender_name"?: string | null
          "sms_sender_name"?: string | null
          "whatsapp_template_booking"?: string | null
          "whatsapp_template_reminder"?: string | null
          "sms_template_reminder"?: string | null
          "created_at"?: string
          "updated_at"?: string
        }
        Update: {
          "id"?: string
          "center_id"?: string
          "whatsapp_enabled"?: boolean
          "sms_enabled"?: boolean
          "reminder_enabled"?: boolean
          "reminder_hours_before"?: number
          "whatsapp_sender_name"?: string | null
          "sms_sender_name"?: string | null
          "whatsapp_template_booking"?: string | null
          "whatsapp_template_reminder"?: string | null
          "sms_template_reminder"?: string | null
          "created_at"?: string
          "updated_at"?: string
        }
        Relationships: [
          {
            foreignKeyName: "notification_settings_center_id_fkey"
            columns: ["center_id"]
            isOneToOne: false
            referencedRelation: "centers"
            referencedColumns: ["id"]
          }
        ]
      }
      "package_entitlement_units": {
        Row: {
          "id": string
          "center_id": string
          "entitlement_id": string
          "service_id": string
          "total_units": number
          "used_units": number
          "created_at": string
        }
        Insert: {
          "id"?: string
          "center_id": string
          "entitlement_id": string
          "service_id": string
          "total_units": number
          "used_units"?: number
          "created_at"?: string
        }
        Update: {
          "id"?: string
          "center_id"?: string
          "entitlement_id"?: string
          "service_id"?: string
          "total_units"?: number
          "used_units"?: number
          "created_at"?: string
        }
        Relationships: [
          {
            foreignKeyName: "package_entitlement_units_center_id_fkey"
            columns: ["center_id"]
            isOneToOne: false
            referencedRelation: "centers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "package_entitlement_units_entitlement_id_fkey"
            columns: ["entitlement_id"]
            isOneToOne: false
            referencedRelation: "customer_entitlements"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "package_entitlement_units_service_id_fkey"
            columns: ["service_id"]
            isOneToOne: false
            referencedRelation: "services"
            referencedColumns: ["id"]
          }
        ]
      }
      "payment_gateway_settings": {
        Row: {
          "id": string
          "center_id": string
          "provider": string
          "is_enabled": boolean
          "is_sandbox": boolean
          "public_key": string | null
          "merchant_identifier": string | null
          "webhook_secret_hint": string | null
          "booking_deposit_enabled": boolean
          "booking_deposit_type": string
          "booking_deposit_value": number
          "success_url": string | null
          "cancel_url": string | null
          "created_at": string
          "updated_at": string
        }
        Insert: {
          "id"?: string
          "center_id": string
          "provider"?: string
          "is_enabled"?: boolean
          "is_sandbox"?: boolean
          "public_key"?: string | null
          "merchant_identifier"?: string | null
          "webhook_secret_hint"?: string | null
          "booking_deposit_enabled"?: boolean
          "booking_deposit_type"?: string
          "booking_deposit_value"?: number
          "success_url"?: string | null
          "cancel_url"?: string | null
          "created_at"?: string
          "updated_at"?: string
        }
        Update: {
          "id"?: string
          "center_id"?: string
          "provider"?: string
          "is_enabled"?: boolean
          "is_sandbox"?: boolean
          "public_key"?: string | null
          "merchant_identifier"?: string | null
          "webhook_secret_hint"?: string | null
          "booking_deposit_enabled"?: boolean
          "booking_deposit_type"?: string
          "booking_deposit_value"?: number
          "success_url"?: string | null
          "cancel_url"?: string | null
          "created_at"?: string
          "updated_at"?: string
        }
        Relationships: [
          {
            foreignKeyName: "payment_gateway_settings_center_id_fkey"
            columns: ["center_id"]
            isOneToOne: false
            referencedRelation: "centers"
            referencedColumns: ["id"]
          }
        ]
      }
      "payments": {
        Row: {
          "id": string
          "center_id": string
          "invoice_id": string
          "amount": number
          "method": string
          "status": string
          "provider_reference": string | null
          "created_at": string
        }
        Insert: {
          "id"?: string
          "center_id": string
          "invoice_id": string
          "amount": number
          "method": string
          "status": string
          "provider_reference"?: string | null
          "created_at"?: string
        }
        Update: {
          "id"?: string
          "center_id"?: string
          "invoice_id"?: string
          "amount"?: number
          "method"?: string
          "status"?: string
          "provider_reference"?: string | null
          "created_at"?: string
        }
        Relationships: [
          {
            foreignKeyName: "payments_center_id_fkey"
            columns: ["center_id"]
            isOneToOne: false
            referencedRelation: "centers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "payments_invoice_center_fk"
            columns: ["invoice_id", "center_id"]
            isOneToOne: false
            referencedRelation: "invoices"
            referencedColumns: ["id", "center_id"]
          }
        ]
      }
      "payroll_line_items": {
        Row: {
          "id": string
          "center_id": string
          "payroll_run_id": string
          "employee_id": string
          "base_salary": number
          "advances_deducted": number
          "net_salary": number
          "notes": string | null
          "created_at": string
          "updated_at": string
        }
        Insert: {
          "id"?: string
          "center_id": string
          "payroll_run_id": string
          "employee_id": string
          "base_salary"?: number
          "advances_deducted"?: number
          "net_salary"?: number
          "notes"?: string | null
          "created_at"?: string
          "updated_at"?: string
        }
        Update: {
          "id"?: string
          "center_id"?: string
          "payroll_run_id"?: string
          "employee_id"?: string
          "base_salary"?: number
          "advances_deducted"?: number
          "net_salary"?: number
          "notes"?: string | null
          "created_at"?: string
          "updated_at"?: string
        }
        Relationships: [
          {
            foreignKeyName: "payroll_line_items_center_id_fkey"
            columns: ["center_id"]
            isOneToOne: false
            referencedRelation: "centers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "payroll_lines_employee_center_fk"
            columns: ["employee_id", "center_id"]
            isOneToOne: false
            referencedRelation: "employees"
            referencedColumns: ["id", "center_id"]
          },
          {
            foreignKeyName: "payroll_lines_run_center_fk"
            columns: ["payroll_run_id", "center_id"]
            isOneToOne: false
            referencedRelation: "payroll_runs"
            referencedColumns: ["id", "center_id"]
          }
        ]
      }
      "payroll_runs": {
        Row: {
          "id": string
          "center_id": string
          "period_month": string
          "run_date": string
          "notes": string | null
          "created_at": string
          "updated_at": string
        }
        Insert: {
          "id"?: string
          "center_id": string
          "period_month": string
          "run_date"?: string
          "notes"?: string | null
          "created_at"?: string
          "updated_at"?: string
        }
        Update: {
          "id"?: string
          "center_id"?: string
          "period_month"?: string
          "run_date"?: string
          "notes"?: string | null
          "created_at"?: string
          "updated_at"?: string
        }
        Relationships: [
          {
            foreignKeyName: "payroll_runs_center_id_fkey"
            columns: ["center_id"]
            isOneToOne: false
            referencedRelation: "centers"
            referencedColumns: ["id"]
          }
        ]
      }
      "products": {
        Row: {
          "id": string
          "center_id": string
          "name": string
          "barcode": string | null
          "price": number
          "cost": number
          "stock_quantity": number
          "created_at": string
          "updated_at": string
          "reorder_level": number
          "is_active": boolean
          "track_inventory": boolean
        }
        Insert: {
          "id"?: string
          "center_id": string
          "name": string
          "barcode"?: string | null
          "price"?: number
          "cost"?: number
          "stock_quantity"?: number
          "created_at"?: string
          "updated_at"?: string
          "reorder_level"?: number
          "is_active"?: boolean
          "track_inventory"?: boolean
        }
        Update: {
          "id"?: string
          "center_id"?: string
          "name"?: string
          "barcode"?: string | null
          "price"?: number
          "cost"?: number
          "stock_quantity"?: number
          "created_at"?: string
          "updated_at"?: string
          "reorder_level"?: number
          "is_active"?: boolean
          "track_inventory"?: boolean
        }
        Relationships: [
          {
            foreignKeyName: "products_center_id_fkey"
            columns: ["center_id"]
            isOneToOne: false
            referencedRelation: "centers"
            referencedColumns: ["id"]
          }
        ]
      }
      "profiles": {
        Row: {
          "id": string
          "full_name": string | null
          "created_at": string
        }
        Insert: {
          "id": string
          "full_name"?: string | null
          "created_at"?: string
        }
        Update: {
          "id"?: string
          "full_name"?: string | null
          "created_at"?: string
        }
        Relationships: [
          {
            foreignKeyName: "profiles_id_fkey"
            columns: ["id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
      "service_categories": {
        Row: {
          "id": string
          "center_id": string
          "name": string
          "created_at": string
        }
        Insert: {
          "id"?: string
          "center_id": string
          "name": string
          "created_at"?: string
        }
        Update: {
          "id"?: string
          "center_id"?: string
          "name"?: string
          "created_at"?: string
        }
        Relationships: [
          {
            foreignKeyName: "service_categories_center_id_fkey"
            columns: ["center_id"]
            isOneToOne: false
            referencedRelation: "centers"
            referencedColumns: ["id"]
          }
        ]
      }
      "service_file_images": {
        Row: {
          "id": string
          "center_id": string
          "service_file_id": string
          "image_kind": string
          "image_url": string
          "sort_order": number
          "created_at": string
        }
        Insert: {
          "id"?: string
          "center_id": string
          "service_file_id": string
          "image_kind": string
          "image_url": string
          "sort_order"?: number
          "created_at"?: string
        }
        Update: {
          "id"?: string
          "center_id"?: string
          "service_file_id"?: string
          "image_kind"?: string
          "image_url"?: string
          "sort_order"?: number
          "created_at"?: string
        }
        Relationships: [
          {
            foreignKeyName: "service_file_images_center_id_fkey"
            columns: ["center_id"]
            isOneToOne: false
            referencedRelation: "centers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "service_file_images_service_file_id_fkey"
            columns: ["service_file_id"]
            isOneToOne: false
            referencedRelation: "service_files"
            referencedColumns: ["id"]
          }
        ]
      }
      "service_files": {
        Row: {
          "id": string
          "center_id": string
          "customer_id": string
          "appointment_id": string | null
          "service_id": string | null
          "title": string
          "note": string | null
          "created_by": string | null
          "created_at": string
          "updated_at": string
        }
        Insert: {
          "id"?: string
          "center_id": string
          "customer_id": string
          "appointment_id"?: string | null
          "service_id"?: string | null
          "title": string
          "note"?: string | null
          "created_by"?: string | null
          "created_at"?: string
          "updated_at"?: string
        }
        Update: {
          "id"?: string
          "center_id"?: string
          "customer_id"?: string
          "appointment_id"?: string | null
          "service_id"?: string | null
          "title"?: string
          "note"?: string | null
          "created_by"?: string | null
          "created_at"?: string
          "updated_at"?: string
        }
        Relationships: [
          {
            foreignKeyName: "service_files_appointment_id_fkey"
            columns: ["appointment_id"]
            isOneToOne: false
            referencedRelation: "appointments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "service_files_center_id_fkey"
            columns: ["center_id"]
            isOneToOne: false
            referencedRelation: "centers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "service_files_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "service_files_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "service_files_service_id_fkey"
            columns: ["service_id"]
            isOneToOne: false
            referencedRelation: "services"
            referencedColumns: ["id"]
          }
        ]
      }
      "service_package_items": {
        Row: {
          "id": string
          "package_id": string
          "service_id": string
          "quantity": number
          "created_at": string
        }
        Insert: {
          "id"?: string
          "package_id": string
          "service_id": string
          "quantity"?: number
          "created_at"?: string
        }
        Update: {
          "id"?: string
          "package_id"?: string
          "service_id"?: string
          "quantity"?: number
          "created_at"?: string
        }
        Relationships: [
          {
            foreignKeyName: "service_package_items_package_id_fkey"
            columns: ["package_id"]
            isOneToOne: false
            referencedRelation: "service_packages"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "service_package_items_service_id_fkey"
            columns: ["service_id"]
            isOneToOne: false
            referencedRelation: "services"
            referencedColumns: ["id"]
          }
        ]
      }
      "service_packages": {
        Row: {
          "id": string
          "center_id": string
          "name": string
          "description": string | null
          "package_price": number
          "is_active": boolean
          "created_at": string
          "updated_at": string
        }
        Insert: {
          "id"?: string
          "center_id": string
          "name": string
          "description"?: string | null
          "package_price": number
          "is_active"?: boolean
          "created_at"?: string
          "updated_at"?: string
        }
        Update: {
          "id"?: string
          "center_id"?: string
          "name"?: string
          "description"?: string | null
          "package_price"?: number
          "is_active"?: boolean
          "created_at"?: string
          "updated_at"?: string
        }
        Relationships: [
          {
            foreignKeyName: "service_packages_center_id_fkey"
            columns: ["center_id"]
            isOneToOne: false
            referencedRelation: "centers"
            referencedColumns: ["id"]
          }
        ]
      }
      "services": {
        Row: {
          "id": string
          "center_id": string
          "name": string
          "category_id": string | null
          "price": number
          "duration_minutes": number
          "is_active": boolean
          "created_at": string
          "updated_at": string
          "pricing_mode": string
          "catalog_code": string | null
        }
        Insert: {
          "id"?: string
          "center_id": string
          "name": string
          "category_id"?: string | null
          "price"?: number
          "duration_minutes"?: number
          "is_active"?: boolean
          "created_at"?: string
          "updated_at"?: string
          "pricing_mode"?: string
          "catalog_code"?: string | null
        }
        Update: {
          "id"?: string
          "center_id"?: string
          "name"?: string
          "category_id"?: string | null
          "price"?: number
          "duration_minutes"?: number
          "is_active"?: boolean
          "created_at"?: string
          "updated_at"?: string
          "pricing_mode"?: string
          "catalog_code"?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "services_category_center_fk"
            columns: ["category_id", "center_id"]
            isOneToOne: false
            referencedRelation: "service_categories"
            referencedColumns: ["id", "center_id"]
          },
          {
            foreignKeyName: "services_center_id_fkey"
            columns: ["center_id"]
            isOneToOne: false
            referencedRelation: "centers"
            referencedColumns: ["id"]
          }
        ]
      }
      "support_tickets": {
        Row: {
          "id": string
          "center_id": string
          "created_by": string
          "route": string | null
          "app_version": string | null
          "environment": string | null
          "role": string | null
          "error_reference": string | null
          "expected_behavior": string | null
          "actual_behavior": string | null
          "contact_email": string | null
          "urgency": string
          "status": string
          "created_at": string
        }
        Insert: {
          "id"?: string
          "center_id": string
          "created_by": string
          "route"?: string | null
          "app_version"?: string | null
          "environment"?: string | null
          "role"?: string | null
          "error_reference"?: string | null
          "expected_behavior"?: string | null
          "actual_behavior"?: string | null
          "contact_email"?: string | null
          "urgency"?: string
          "status"?: string
          "created_at"?: string
        }
        Update: {
          "id"?: string
          "center_id"?: string
          "created_by"?: string
          "route"?: string | null
          "app_version"?: string | null
          "environment"?: string | null
          "role"?: string | null
          "error_reference"?: string | null
          "expected_behavior"?: string | null
          "actual_behavior"?: string | null
          "contact_email"?: string | null
          "urgency"?: string
          "status"?: string
          "created_at"?: string
        }
        Relationships: [
          {
            foreignKeyName: "support_tickets_center_id_fkey"
            columns: ["center_id"]
            isOneToOne: false
            referencedRelation: "centers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "support_tickets_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
    }
    Views: Record<string, never>
    Functions: {
      "add_customer_notification_event_v1": {
        Args: { "p_center_id": string | null; "p_customer_id": string | null; "p_appointment_id": string | null; "p_channel": string | null; "p_direction": string | null; "p_template_key": string | null; "p_message_preview": string | null; "p_delivery_status": string | null; "p_sent_at": string | null }
        Returns: Json
      },
      "add_customer_support_note_v1": {
        Args: { "p_center_id": string | null; "p_customer_id": string | null; "p_note": string | null }
        Returns: Json
      },
      "admin_create_employee_v1": {
        Args: { "p_center_id": string | null; "p_employee": Json | null }
        Returns: Json
      },
      "admin_deactivate_employee_v1": {
        Args: { "p_center_id": string | null; "p_employee_id": string | null; "p_reason": string | null }
        Returns: Json
      },
      "admin_delete_employee_v1": {
        Args: { "p_center_id": string | null; "p_employee_id": string | null }
        Returns: Json
      },
      "admin_global_search_v1": {
        Args: { "p_center_id": string | null; "p_query": string | null; "p_limit": number | null }
        Returns: Json
      },
      "admin_reactivate_employee_v1": {
        Args: { "p_center_id": string | null; "p_employee_id": string | null; "p_reason": string | null }
        Returns: Json
      },
      "admin_update_employee_v1": {
        Args: { "p_center_id": string | null; "p_employee_id": string | null; "p_patch": Json | null }
        Returns: Json
      },
      "check_notification_dedup_v1": {
        Args: { "p_center_id": string | null; "p_dedup_key": string | null; "p_window_minutes": number | null }
        Returns: boolean
      },
      "claim_notification_dedup_v1": {
        Args: { "p_center_id": string | null; "p_dedup_key": string | null; "p_window_minutes": number | null }
        Returns: boolean
      },
      "create_accounting_journal_entry_admin_impl_v1": {
        Args: { "p_center_id": string | null; "p_entry_date": string | null; "p_entry_type": string | null; "p_reference_type": string | null; "p_reference_id": string | null; "p_description": string | null; "p_debit_account": string | null; "p_credit_account": string | null; "p_amount": number | null; "p_currency": string | null }
        Returns: Json
      },
      "create_accounting_journal_entry_v1": {
        Args: { "p_center_id": string | null; "p_entry_date": string | null; "p_entry_type": string | null; "p_reference_type": string | null; "p_reference_id": string | null; "p_description": string | null; "p_debit_account": string | null; "p_credit_account": string | null; "p_amount": number | null; "p_currency": string | null }
        Returns: Json
      },
      "create_ai_booking_lead_admin_impl_v1": {
        Args: { "p_center_id": string | null; "p_customer_name": string | null; "p_customer_phone": string | null; "p_preferred_service_id": string | null; "p_preferred_date": string | null; "p_source_channel": string | null; "p_summary": string | null }
        Returns: Json
      },
      "create_ai_booking_lead_v1": {
        Args: { "p_center_id": string | null; "p_customer_name": string | null; "p_customer_phone": string | null; "p_preferred_service_id": string | null; "p_preferred_date": string | null; "p_source_channel": string | null; "p_summary": string | null }
        Returns: Json
      },
      "create_customer_review_admin_impl_v1": {
        Args: { "p_center_id": string | null; "p_customer_id": string | null; "p_appointment_id": string | null; "p_rating": number | null; "p_comment": string | null; "p_is_published": boolean | null }
        Returns: Json
      },
      "create_customer_review_v1": {
        Args: { "p_center_id": string | null; "p_customer_id": string | null; "p_appointment_id": string | null; "p_rating": number | null; "p_comment": string | null; "p_is_published": boolean | null }
        Returns: Json
      },
      "create_payroll_run_v1": {
        Args: { "p_center_id": string | null; "p_period_month": string | null; "p_notes": string | null }
        Returns: Json
      },
      "create_service_file_admin_impl_v1": {
        Args: { "p_center_id": string | null; "p_customer_id": string | null; "p_appointment_id": string | null; "p_service_id": string | null; "p_title": string | null; "p_note": string | null; "p_before_images": string[] | null; "p_after_images": string[] | null; "p_reference_images": string[] | null }
        Returns: Json
      },
      "create_service_file_v1": {
        Args: { "p_center_id": string | null; "p_customer_id": string | null; "p_appointment_id": string | null; "p_service_id": string | null; "p_title": string | null; "p_note": string | null; "p_before_images": string[] | null; "p_after_images": string[] | null; "p_reference_images": string[] | null }
        Returns: Json
      },
      "create_service_package_v1": {
        Args: { "p_center_id": string | null; "p_name": string | null; "p_description": string | null; "p_package_price": number | null; "p_items": Json | null }
        Returns: Json
      },
      "create_support_ticket_v1": {
        Args: { "p_center_id": string | null; "p_route": string | null; "p_app_version": string | null; "p_environment": string | null; "p_role": string | null; "p_error_reference": string | null; "p_expected_behavior": string | null; "p_actual_behavior": string | null; "p_contact_email": string | null; "p_urgency": string | null }
        Returns: Json
      },
      "delete_payroll_run_v1": {
        Args: { "p_center_id": string | null; "p_payroll_run_id": string | null }
        Returns: Json
      },
      "expire_entitlement_admin_impl_v1": {
        Args: { "p_entitlement_id": string | null; "p_reason": string | null; "p_actor_employee_id": string | null }
        Returns: Json
      },
      "expire_entitlement_v1": {
        Args: { "p_entitlement_id": string | null; "p_reason": string | null; "p_actor_employee_id": string | null }
        Returns: Json
      },
      "get_dashboard_pnl_v1": {
        Args: { "p_center_id": string | null; "p_from": string | null; "p_to": string | null }
        Returns: Json
      },
      "get_dashboard_revenue_entries_v1": {
        Args: { "p_center_id": string | null; "p_from": string | null; "p_to": string | null }
        Returns: Json
      },
      "get_dashboard_summary_v1": {
        Args: { "p_center_id": string | null; "p_day_start": string | null; "p_day_end": string | null; "p_month_start": string | null }
        Returns: Json
      },
      "issue_gift_card_v1": {
        Args: { "p_center_id": string | null; "p_code": string | null; "p_initial_balance": number | null; "p_customer_id": string | null; "p_note": string | null; "p_expires_at": string | null }
        Returns: Json
      },
      "list_admin_audit_events_v1": {
        Args: { "p_center_id": string | null; "p_limit": number | null; "p_offset": number | null; "p_action": string | null; "p_target_type": string | null }
        Returns: Json
      },
      "list_customer_notification_preferences_v1": {
        Args: { "p_center_id": string | null; "p_customer_id": string | null }
        Returns: Json
      },
      "list_customer_support_notes_v1": {
        Args: { "p_center_id": string | null; "p_customer_id": string | null; "p_limit": number | null }
        Returns: Json
      },
      "list_employees_v1": {
        Args: { "p_center_id": string | null }
        Returns: Json
      },
      "list_support_tickets_v1": {
        Args: { "p_center_id": string | null; "p_limit": number | null }
        Returns: Json
      },
      "mark_appointment_no_show_v1": {
        Args: { "p_center_id": string | null; "p_appointment_id": string | null; "p_charge_no_show_fee": boolean | null; "p_note": string | null }
        Returns: Json
      },
      "opt_out_customer_notification_v1": {
        Args: { "p_opt_in_token": string | null }
        Returns: Json
      },
      "process_checkout_idempotent_v1": {
        Args: { "p_request_id": string | null; "p_center_id": string | null; "p_customer_id": string | null; "p_employee_id": string | null; "p_payment_method": string | null; "p_discount_amount": number | null; "p_use_loyalty_points": boolean | null; "p_items": Json | null; "p_gift_card_code": string | null; "p_entitlement_redemptions": Json | null }
        Returns: Json
      },
      "process_checkout_v1": {
        Args: { "p_center_id": string | null; "p_customer_id": string | null; "p_employee_id": string | null; "p_payment_method": string | null; "p_discount_amount": number | null; "p_use_loyalty_points": boolean | null; "p_items": Json | null; "p_gift_card_code": string | null; "p_entitlement_redemptions": Json | null }
        Returns: Json
      },
      "public_cancel_booking_v1": {
        Args: { "p_center_id": string | null; "p_appointment_id": string | null; "p_phone": string | null; "p_portal_token": string | null; "p_reason": string | null }
        Returns: Json
      },
      "public_center_info_v1": {
        Args: { "p_center_id": string | null }
        Returns: unknown
      },
      "public_client_portal_login_v1": {
        Args: { "p_center_id": string | null; "p_phone": string | null; "p_token": string | null }
        Returns: Json
      },
      "public_client_portal_profile_v1": {
        Args: { "p_center_id": string | null; "p_customer_id": string | null; "p_phone": string | null; "p_token": string | null }
        Returns: Json
      },
      "public_client_portal_profile_v2": {
        Args: { "p_center_id": string | null; "p_customer_id": string | null; "p_phone": string | null; "p_token": string | null }
        Returns: Json
      },
      "public_create_booking_v1": {
        Args: { "p_center_id": string | null; "p_service_id": string | null; "p_employee_id": string | null; "p_customer_name": string | null; "p_customer_phone": string | null; "p_date_time": string | null; "p_notes": string | null }
        Returns: Json
      },
      "public_list_services_v1": {
        Args: { "p_center_id": string | null }
        Returns: unknown
      },
      "public_list_staff_v1": {
        Args: { "p_center_id": string | null }
        Returns: unknown
      },
      "public_reschedule_booking_v1": {
        Args: { "p_center_id": string | null; "p_appointment_id": string | null; "p_phone": string | null; "p_portal_token": string | null; "p_new_date_time": string | null; "p_new_employee_id": string | null; "p_reason": string | null }
        Returns: Json
      },
      "public_taken_slots_v1": {
        Args: { "p_center_id": string | null; "p_day": string | null }
        Returns: unknown
      },
      "refund_entitlement_admin_impl_v1": {
        Args: { "p_entitlement_id": string | null; "p_amount": number | null; "p_reason": string | null; "p_actor_employee_id": string | null }
        Returns: Json
      },
      "refund_entitlement_v1": {
        Args: { "p_entitlement_id": string | null; "p_amount": number | null; "p_reason": string | null; "p_actor_employee_id": string | null }
        Returns: Json
      },
      "release_notification_dedup_v1": {
        Args: { "p_center_id": string | null; "p_dedup_key": string | null }
        Returns: boolean
      },
      "rotate_customer_portal_token_v1": {
        Args: { "p_center_id": string | null; "p_customer_id": string | null }
        Returns: Json
      },
      "upsert_customer_notification_preference_v1": {
        Args: { "p_center_id": string | null; "p_customer_id": string | null; "p_channel": string | null; "p_opt_in": boolean | null; "p_quiet_hour_start": string | null; "p_quiet_hour_end": string | null }
        Returns: Json
      },
      "upsert_notification_settings_admin_impl_v1": {
        Args: { "p_center_id": string | null; "p_whatsapp_enabled": boolean | null; "p_sms_enabled": boolean | null; "p_reminder_enabled": boolean | null; "p_reminder_hours_before": number | null; "p_whatsapp_sender_name": string | null; "p_sms_sender_name": string | null; "p_whatsapp_template_booking": string | null; "p_whatsapp_template_reminder": string | null; "p_sms_template_reminder": string | null }
        Returns: Json
      },
      "upsert_notification_settings_v1": {
        Args: { "p_center_id": string | null; "p_whatsapp_enabled": boolean | null; "p_sms_enabled": boolean | null; "p_reminder_enabled": boolean | null; "p_reminder_hours_before": number | null; "p_whatsapp_sender_name": string | null; "p_sms_sender_name": string | null; "p_whatsapp_template_booking": string | null; "p_whatsapp_template_reminder": string | null; "p_sms_template_reminder": string | null }
        Returns: Json
      },
      "upsert_payment_gateway_settings_admin_impl_v1": {
        Args: { "p_center_id": string | null; "p_provider": string | null; "p_is_enabled": boolean | null; "p_is_sandbox": boolean | null; "p_public_key": string | null; "p_merchant_identifier": string | null; "p_webhook_secret_hint": string | null; "p_booking_deposit_enabled": boolean | null; "p_booking_deposit_type": string | null; "p_booking_deposit_value": number | null; "p_success_url": string | null; "p_cancel_url": string | null }
        Returns: Json
      },
      "upsert_payment_gateway_settings_v1": {
        Args: { "p_center_id": string | null; "p_provider": string | null; "p_is_enabled": boolean | null; "p_is_sandbox": boolean | null; "p_public_key": string | null; "p_merchant_identifier": string | null; "p_webhook_secret_hint": string | null; "p_booking_deposit_enabled": boolean | null; "p_booking_deposit_type": string | null; "p_booking_deposit_value": number | null; "p_success_url": string | null; "p_cancel_url": string | null }
        Returns: Json
      },
      "void_entitlement_admin_impl_v1": {
        Args: { "p_entitlement_id": string | null; "p_reason": string | null; "p_actor_employee_id": string | null }
        Returns: Json
      },
      "void_entitlement_v1": {
        Args: { "p_entitlement_id": string | null; "p_reason": string | null; "p_actor_employee_id": string | null }
        Returns: Json
      },
      "write_admin_audit_event_v1": {
        Args: { "p_center_id": string | null; "p_action": string | null; "p_target_type": string | null; "p_target_id": string | null; "p_target_summary": string | null; "p_reason": string | null; "p_details": Json | null }
        Returns: Json
      }
    }
    Enums: {
      "appointment_status": "SCHEDULED" | "COMPLETED" | "CANCELLED" | "NO_SHOW"
    }
    CompositeTypes: Record<string, never>
  }
};

export type Tables<T extends keyof Database["public"]["Tables"]> = Database["public"]["Tables"][T]["Row"];
export type TablesInsert<T extends keyof Database["public"]["Tables"]> = Database["public"]["Tables"][T]["Insert"];
export type TablesUpdate<T extends keyof Database["public"]["Tables"]> = Database["public"]["Tables"][T]["Update"];
